' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET

    Public Partial Class AddNewUser

        Protected Content1 As System.Web.UI.WebControls.Content

        Protected Content3 As System.Web.UI.WebControls.Content

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected InvalidUserNameOrPasswordMessage As System.Web.UI.WebControls.Label

        Protected Username As System.Web.UI.WebControls.TextBox

        Protected Password As System.Web.UI.WebControls.TextBox

        Protected Email As System.Web.UI.WebControls.TextBox

        Protected SecurityQuestion As System.Web.UI.WebControls.Label

        Protected SecurityAnswer As System.Web.UI.WebControls.TextBox

        Protected CreateAccountButton As System.Web.UI.WebControls.Button

        Protected CreateAccountResults As System.Web.UI.WebControls.Label

    End Class

End Namespace