' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET

    Public Partial Class ChangePassword

        Protected Content1 As System.Web.UI.WebControls.Content

        Protected lblHeader As System.Web.UI.HtmlControls.HtmlGenericControl

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected ChangePwdCtrl As System.Web.UI.WebControls.ChangePassword

        Protected CurrentPassword As System.Web.UI.WebControls.TextBox

        Protected NewPassword As System.Web.UI.WebControls.TextBox

        Protected ConfirmNewPassword As System.Web.UI.WebControls.TextBox

        Protected ChangePasswordPushButton As System.Web.UI.WebControls.Button

        Protected CancelPushButton As System.Web.UI.WebControls.Button

        Protected FailureText As System.Web.UI.WebControls.Literal

        Protected ContinuePushButton As System.Web.UI.WebControls.Button

    End Class

End Namespace