
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET

    Partial Public Class RebuildDatabase

        ' <summary>
        ' PanelWelcome control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents PanelWelcome As Global.System.Web.UI.WebControls.Panel

        ' <summary>
        ' labelMessage control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents labelMessage As Global.System.Web.UI.WebControls.Literal

        ' <summary>
        ' dropDownDataProvider control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents dropDownDataProvider As Global.System.Web.UI.WebControls.DropDownList

        ' <summary>
        ' txtFilePath control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents txtFilePath As Global.System.Web.UI.WebControls.TextBox

        ' <summary>
        ' txtClientExecutable control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents txtClientExecutable As Global.System.Web.UI.WebControls.TextBox

        ' <summary>
        ' txtServer control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents txtServer As Global.System.Web.UI.WebControls.TextBox

        ' <summary>
        ' txtPort control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents txtPort As Global.System.Web.UI.WebControls.TextBox

        ' <summary>
        ' txtDatabase control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents txtDatabase As Global.System.Web.UI.WebControls.TextBox

        ' <summary>
        ' txtUserName control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents txtUserName As Global.System.Web.UI.WebControls.TextBox

        ' <summary>
        ' txtPassword control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

        ' <summary>
        ' PanelSuccess control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents PanelSuccess As Global.System.Web.UI.WebControls.Panel

        ' <summary>
        ' labelSuccess control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents labelSuccess As Global.System.Web.UI.WebControls.Literal

        ' <summary>
        ' PanelError control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents PanelError As Global.System.Web.UI.WebControls.Panel

        ' <summary>
        ' labelError control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents labelError As Global.System.Web.UI.WebControls.Literal

        ' <summary>
        ' btnTestConfiguration control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents btnTestConfiguration As Global.System.Web.UI.WebControls.Button

        ' <summary>
        ' PanelRebuildFailure control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents PanelRebuildFailure As Global.System.Web.UI.WebControls.Panel

        ' <summary>
        ' labelRebuildFailure control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents labelRebuildFailure As Global.System.Web.UI.WebControls.Literal

        ' <summary>
        ' PanelRebuildSuccess control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents PanelRebuildSuccess As Global.System.Web.UI.WebControls.Panel

        ' <summary>
        ' labelRebuildSuccess control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents labelRebuildSuccess As Global.System.Web.UI.WebControls.Literal

        ' <summary>
        ' btnRebuildDatabase control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents btnRebuildDatabase As Global.System.Web.UI.WebControls.Button

        ' <summary>
        ' lblStatus control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        ' <summary>
        ' lblOutput control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents lblOutput As Global.System.Web.UI.WebControls.Label

        ' <summary>
        ' grdView control.
        ' </summary>
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents grdView As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
