vbnet
' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET

    Partial Public Class ProxySetup
        Protected Content1 As System.Web.UI.WebControls.Content

        Protected Content3 As System.Web.UI.WebControls.Content

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected valNameRequired As System.Web.UI.WebControls.RequiredFieldValidator

        Protected valRegEx As System.Web.UI.WebControls.RegularExpressionValidator

        Protected txtName As System.Web.UI.WebControls.TextBox

        Protected btnReverse As System.Web.UI.WebControls.Button

        Protected lblOutput As System.Web.UI.WebControls.Label
    End Class

End Namespace
