
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET.resources.Master_Pages

    Public Partial Class SiteNew

        ''' <summary>
        ''' Head1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

        ''' <summary>
        ''' HeadContentPlaceHolder control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents HeadContentPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder

        ''' <summary>
        ''' Form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' A1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

        ''' <summary>
        ''' HeadLoginView control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents HeadLoginView As Global.System.Web.UI.WebControls.LoginView

        ''' <summary>
        ''' lbtGenerateTestData control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents lbtGenerateTestData As Global.System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' HeadLoginStatus control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents HeadLoginStatus As Global.System.Web.UI.WebControls.LoginStatus

        ''' <summary>
        ''' SiteMapDataSource1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents SiteMapDataSource1 As Global.System.Web.UI.WebControls.SiteMapDataSource

        ''' <summary>
        ''' rptrMenu control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents rptrMenu As Global.System.Web.UI.WebControls.Repeater

        ''' <summary>
        ''' SiteMapPath1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents SiteMapPath1 As Global.System.Web.UI.WebControls.SiteMapPath

        ''' <summary>
        ''' ltlMessage control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents ltlMessage As Global.System.Web.UI.WebControls.Literal

        ''' <summary>
        ''' HelpContentPlaceholder control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents HelpContentPlaceholder As Global.System.Web.UI.WebControls.ContentPlaceHolder

        ''' <summary>
        ''' BodyContentPlaceholder control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Friend WithEvents BodyContentPlaceholder As Global.System.Web.UI.WebControls.ContentPlaceHolder

    End Class
End Namespace
