
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET.resources.Master_Pages
    Partial Public Class Site

        ' Head1 control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

        ' HeadContentPlaceHolder control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents HeadContentPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder

        ' Form1 control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ' A1 control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

        ' HeadLoginView control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents HeadLoginView As Global.System.Web.UI.WebControls.LoginView

        ' lbtGenerateTestData control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents lbtGenerateTestData As Global.System.Web.UI.WebControls.LinkButton

        ' HeadLoginStatus control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents HeadLoginStatus As Global.System.Web.UI.WebControls.LoginStatus

        ' SiteMapDataSource1 control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents SiteMapDataSource1 As Global.System.Web.UI.WebControls.SiteMapDataSource

        ' rptrMenu control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents rptrMenu As Global.System.Web.UI.WebControls.Repeater

        ' SiteMapPath1 control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents SiteMapPath1 As Global.System.Web.UI.WebControls.SiteMapPath

        ' ltlMessage control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents ltlMessage As Global.System.Web.UI.WebControls.Literal

        ' HelpContentPlaceholder control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents HelpContentPlaceholder As Global.System.Web.UI.WebControls.ContentPlaceHolder

        ' BodyContentPlaceholder control
        ' <remarks>
        ' Auto-generated field.
        ' To modify move field declaration from designer file to code-behind file.
        ' </remarks>
        Protected WithEvents BodyContentPlaceholder As Global.System.Web.UI.WebControls.ContentPlaceHolder
    End Class
End Namespace
