' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET.Content
    Partial Public Class MessageDigest
        Protected Content1 As System.Web.UI.WebControls.Content

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected lblDigest As System.Web.UI.WebControls.Label

        Protected txtBoxMsg As System.Web.UI.WebControls.TextBox

        Protected btnDigest As System.Web.UI.WebControls.Button

        Protected lblResultDigest As System.Web.UI.WebControls.Label

        Protected Content3 As System.Web.UI.WebControls.Content
    End Class
End Namespace