' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------
Imports System
Imports System.Web
Imports System.Web.UI

Namespace OWASP.WebGoat.NET
    Partial Public Class RegexDoS
        Protected Content1 As System.Web.UI.WebControls.Content
        Protected Content2 As System.Web.UI.WebControls.Content
        Protected lblError As System.Web.UI.WebControls.Label
        Protected txtUsername As System.Web.UI.WebControls.TextBox
        Protected txtPassword As System.Web.UI.WebControls.TextBox
        Protected btnUpload As System.Web.UI.WebControls.Button
    End Class
End Namespace