
' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET

    Public Partial Class SQLInjection

        Protected Content3 As System.Web.UI.WebControls.Content

        Protected Content1 As System.Web.UI.WebControls.Content

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected txtName As System.Web.UI.WebControls.TextBox

        Protected btnAdd As System.Web.UI.WebControls.Button

        Protected lblOutput As System.Web.UI.WebControls.Label

        Protected grdEmail As System.Web.UI.WebControls.GridView

    End Class

End Namespace

