
' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET

    Partial Public Class StoredXSS

        Protected Content3 As System.Web.UI.WebControls.Content

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected lblOutput As System.Web.UI.WebControls.Label

        Protected lblMessage As System.Web.UI.WebControls.Label

        Protected lblComments As System.Web.UI.WebControls.Label

        Protected Table1 As System.Web.UI.WebControls.Table

        Protected TableRow1 As System.Web.UI.WebControls.TableRow

        Protected TableCell1 As System.Web.UI.WebControls.TableCell

        Protected TableCell2 As System.Web.UI.WebControls.TableCell

        Protected txtEmail As System.Web.UI.WebControls.TextBox

        Protected TableRow2 As System.Web.UI.WebControls.TableRow

        Protected TableCell3 As System.Web.UI.WebControls.TableCell

        Protected TableCell4 As System.Web.UI.WebControls.TableCell

        Protected txtComment As System.Web.UI.WebControls.TextBox

        Protected TableRow3 As System.Web.UI.WebControls.TableRow

        Protected TableCell5 As System.Web.UI.WebControls.TableCell

        Protected TableCell6 As System.Web.UI.WebControls.TableCell

        Protected btnSave As System.Web.UI.WebControls.Button

    End Class

End Namespace
