' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET

    Partial Public Class UploadPathManipulation

        Protected Content3 As System.Web.UI.WebControls.Content

        Protected Content1 As System.Web.UI.WebControls.Content

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected labelUpload As System.Web.UI.WebControls.Label

        Protected FileUpload1 As System.Web.UI.WebControls.FileUpload

        Protected btnUpload As System.Web.UI.WebControls.Button

    End Class

End Namespace