'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET.WebGoatCoins

    Public Partial Class AddNewCustomer

        ''' <summary>
        ''' InvalidUserNameOrPasswordMessage control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected WithEvents InvalidUserNameOrPasswordMessage As Global.System.Web.UI.WebControls.Label
        
        ''' <summary>
        ''' Username control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected WithEvents Username As Global.System.Web.UI.WebControls.TextBox
        
        ''' <summary>
        ''' Email control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected WithEvents Email As Global.System.Web.UI.WebControls.TextBox
        
        ''' <summary>
        ''' Password control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected WithEvents Password As Global.System.Web.UI.WebControls.TextBox
        
        ''' <summary>
        ''' IsAdmin control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected WithEvents IsAdmin As Global.System.Web.UI.WebControls.CheckBox
        
        ''' <summary>
        ''' CreateCustomerButton control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected WithEvents CreateCustomerButton As Global.System.Web.UI.WebControls.Button
        
        ''' <summary>
        ''' CreateAccountResults control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected WithEvents CreateAccountResults As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace