' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET.WebGoatCoins

    Public Partial Class ChangePassword

        Protected Content1 As System.Web.UI.WebControls.Content

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected Content3 As System.Web.UI.WebControls.Content

        Protected labelMessage As System.Web.UI.WebControls.Literal

        Protected txtPassword1 As System.Web.UI.WebControls.TextBox

        Protected txtPassword2 As System.Web.UI.WebControls.TextBox

        Protected ButtonChangePassword As System.Web.UI.WebControls.Button

    End Class

End Namespace
