' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET.WebGoatCoins

    Public Partial Class ForgotPassword

        Protected Content1 As System.Web.UI.WebControls.Content

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected Content3 As System.Web.UI.WebControls.Content

        Protected PanelForgotPasswordStep1 As System.Web.UI.WebControls.Panel

        Protected labelMessage As System.Web.UI.WebControls.Literal

        Protected txtEmail As System.Web.UI.WebControls.TextBox

        Protected ButtonCheckEmail As System.Web.UI.WebControls.Button

        Protected PanelForgotPasswordStep2 As System.Web.UI.WebControls.Panel

        Protected labelQuestion As System.Web.UI.WebControls.Literal

        Protected txtAnswer As System.Web.UI.WebControls.TextBox

        Protected ButtonCheckAnswer As System.Web.UI.WebControls.Button

        Protected PanelForgotPasswordStep3 As System.Web.UI.WebControls.Panel

        Protected labelPassword As System.Web.UI.WebControls.Literal

        Protected ButtonCustomerLogin As System.Web.UI.WebControls.Button

    End Class

End Namespace