' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET

    Public Partial Class MainPage

        Protected Content3 As System.Web.UI.WebControls.Content

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected labelOutput As System.Web.UI.WebControls.Label

        Protected labelMessage As System.Web.UI.WebControls.Literal

        Protected labelWelcome As System.Web.UI.WebControls.Literal

        Protected Image1 As System.Web.UI.WebControls.Image

        Protected labelUpload As System.Web.UI.WebControls.Label

        Protected CustomerTable As System.Web.UI.WebControls.Table

        Protected FileUpload1 As System.Web.UI.WebControls.FileUpload

        Protected btnUpload As System.Web.UI.WebControls.Button

    End Class

End Namespace