'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET.WebGoatCoins

    Partial Public Class Messages

        ''' <summary>
        ''' lblMessages control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected WithEvents lblMessages As System.Web.UI.WebControls.Label
    End Class

End Namespace