' ------------------------------------------------------------------------------
'  <autogenerated>
'      This code was generated by a tool.
'      Mono Runtime Version: 4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if 
'      the code is regenerated.
'  </autogenerated>
' ------------------------------------------------------------------------------

Namespace OWASP.WebGoat.NET.WebGoatCoins

    Public Partial Class Orders

        Protected Content1 As System.Web.UI.WebControls.Content

        Protected Content2 As System.Web.UI.WebControls.Content

        Protected Content3 As System.Web.UI.WebControls.Content

        Protected labelMessage As System.Web.UI.WebControls.Literal

        Protected lblOutput As System.Web.UI.WebControls.Label

        Protected GridView1 As System.Web.UI.WebControls.GridView

        Protected PanelShowDetailSuccess As System.Web.UI.WebControls.Panel

        Protected litSuccessDetailMessage As System.Web.UI.WebControls.Literal

        Protected PanelShowDetailFailure As System.Web.UI.WebControls.Panel

        Protected litErrorDetailMessage As System.Web.UI.WebControls.Literal

        Protected PanelShowDetails As System.Web.UI.WebControls.Panel

        Protected DetailsView1 As System.Web.UI.WebControls.DetailsView

        Protected HyperLink1 As System.Web.UI.WebControls.HyperLink

    End Class

End Namespace